### PR TITLE
feat(middleware): Add 'symbolMiddleware' and 'symbolInstanceMiddleware'

### LINKED ISSUE #18: Not able to perform consistent sync of Sketch Library File
Hey there, 

to be honest, I'm blown away how easily this turns my html into sketch symbols. Big props for that. 

Let me explain what I'm struggling with:

1. I turn a html file into the `asketch.json` file
1. I trigger the sketch plugin and select both files
1. I save that file
1. I link the saved filed in the preferences as a library
1. I create a new file and use the symbols from the library
1. I update the html and perform step 1-3

I'd expect to have this 
image
in my sketch but it does not appear. I'm able to use the updated symbols from the library but **already used symbols** are not updated.

Do you know this issue or  how to fix it? 

thanks for the awesome work <3

### PR DESCRIPTION
**Pull request by mnikkane**
This allows for example setting static ID for the symbol master, which seems to fix at least partially #18. This also allows modifying symbol instances. Usage guide is provided in the readme.

Done similarly as symbol layers middleware in PR #39

### CODE REVIEW

**Comment by markdalgleish** [comment]
Thank you so much for your PR! This looks really great.

I feel like we should also add `symbolMiddleware` at the same time to make this a complete feature. Are you open to doing this work? If not, I'm happy to find some time to pick up this branch.

**Comment by mnikkane** [comment]
Hi, I could check that, should be good addition. 

As the codebase is not that familiar to me, just double checking that do you mean adding middleware for symbol instances around https://github.com/seek-oss/html-sketchapp-cli/blob/master/script/generateAlmostSketch.js#L35 and passing node and symbolMaster as a parameters? Maybe name this new middleware to `symbolInstanceMiddleware` (or is `symbolMiddleware` enough)?

**Comment by markdalgleish** [comment]
I was thinking just regular symbols (`data-sketch-symbol`), but it makes sense for symbol instances too, so I'd say we need both `symbolMiddleware` and `symbolInstanceMiddleware`.

**Comment by mnikkane** [comment]
Does't the `symbolMasterMiddleware` already handle the regular symbols (`data-sketch-symbol`) in line 97: https://github.com/seek-oss/html-sketchapp-cli/pull/52/files#diff-7c5a4658631b0df813b5f5188bed6f16R97

Or am I missing something here 🤔?

**Comment by markdalgleish** [comment]
Ah sorry, you're right. Forgot that all non-instance symbols are technically symbol masters.

I think the API should mirror the terminology we use in the data attributes.

`<div data-sketch-symbol="...">` goes through `symbolMiddleware`.
`<div data-sketch-symbol-instance="...">` goes through `symbolInstanceMiddleware`.

**Comment by mnikkane** [comment]
Renamed the symbolMasterMiddleware to symbolMiddleware and added also symbolInstanceMiddleware (as I do not have own use case for it, so please tell if improvements needed). 

Also fixed tests to pass with html-sketchapp 3.3.0 (hasClippingMask and clippingMaskMode was added added to asketch output in 3.3.0)

**Comment by markdalgleish** [comment]
Thanks so much for this PR, and for your patience! 👏🏻

I refactored the code a little, tweaked the documentation, and published as [v0.6.0](https://github.com/seek-oss/html-sketchapp-cli/releases/tag/v0.6.0) 🚀 🎉

**Comment by mnikkane** [comment]
Nice refactorings, excellent. 

Thanks!

**Pull request merged**
