### PR TITLE
feat(ids): Support custom IDs for Sketch library sync

### PR DESCRIPTION
**Pull request by macintoshhelper**
This adds a document/page name option in the config together with a `customIds` opt-in option that uses permanent IDs for shared styles in `html-sketchapp` if you know all IDs (`data-sketch-text`) are unique and will not change.

This PR should fix library sync between updates (symbols can have a permanent ID).

Documentation should probably be added to the `README.md` for setting symbol IDs:
```js
  symbolMiddleware: ({ symbol, node, suffix }) => {
    const symbolName = node.dataset.sketchSymbol;

    symbol.setId(`${symbolName}${suffix}`);
    symbol.setName(symbolName);
  },
```

New config options:
```js
{
  name: 'project-id-here',
  customIds: true
}
```

Depends on changes in https://github.com/brainly/html-sketchapp/pull/151 (that would need to be merged first).

#18

### CODE REVIEW

**Comment by macintoshhelper** [comment]
`symbol-middleware.test.js` fails because of a snapshot test mismatch. Not sure what's causing this and whether it's safe to override the snapshot test.

**Comment by markdalgleish** [comment]
Hey, thanks for this PR! Definitely keen to support this behaviour. However, since we're unable to merge this PR until https://github.com/brainly/html-sketchapp/pull/151 is merged first, I'm closing this for now. Please feel free to reopen once this is no longer the case.

**Comment by michalsnik** [comment]
The brainly/html-sketchapp#151 has been merged, can you please reopen this PR @macintoshhelper @markdalgleish ? :)

**Comment by macintoshhelper** [comment]
I've reopened it with changes for the new text middleware, apologies for the delay!

> @michalsnik @markdalgleish

**Pull request closed without merging**
